import axios from 'axios';
import config from '../../../config';

export const createPlan = async (): Promise<Record<string, unknown>> => {
  const {status, data} = await axios({
    url: 'https://api-m.sandbox.paypal.com/v1/billing/plans',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: `Bearer ${config.paypal.access_token}`,
      Prefer: 'return=representation',
    },
    params: {
      // generated by creatProduct
      product_id: 'PROD-7LR12491RA623190V',
      name: 'Basic Plan',
      description: 'Basic plan',
      billing_cycles: [
        {
          frequency: {
            interval_unit: 'MONTH',
            interval_count: 1,
          },
          tenure_type: 'TRIAL',
          sequence: 1,
          total_cycles: 1,
        },
        {
          frequency: {
            interval_unit: 'MONTH',
            interval_count: 1,
          },
          tenure_type: 'REGULAR',
          sequence: 2,
          total_cycles: 12,
          pricing_scheme: {
            fixed_price: {
              value: '10',
              currency_code: 'USD',
            },
          },
        },
      ],
      payment_preferences: {
        service_type: 'PREPAID',
        auto_bill_outstanding: true,
        setup_fee: {
          value: '10',
          currency_code: 'USD',
        },
        setup_fee_failure_action: 'CONTINUE',
        payment_failure_threshold: 3,
      },
      quantity_supported: true,
      taxes: {
        percentage: '10',
        inclusive: false,
      },
    },
  });

  return {status, data};
};

/**
status code 201
{
  "id": "P-4DB5144860082564AMEIREZI",
  "product_id": "PROD-7LR12491RA623190V",
  "name": "Basic Plan",
  "status": "ACTIVE",
  "description": "asic plan",
  "usage_type": "LICENSED",
  "billing_cycles": [
    {
      "frequency": {
        "interval_unit": "MONTH",
        "interval_count": 1
      },
      "tenure_type": "TRIAL",
      "sequence": 1,
      "total_cycles": 1
    },
    {
      "pricing_scheme": {
        "version": 1,
        "fixed_price": {
          "currency_code": "USD",
          "value": "10.0"
        },
        "create_time": "2021-08-09T11:32:53Z",
        "update_time": "2021-08-09T11:32:53Z"
      },
      "frequency": {
        "interval_unit": "MONTH",
        "interval_count": 1
      },
      "tenure_type": "REGULAR",
      "sequence": 2,
      "total_cycles": 12
    }
  ],
  "payment_preferences": {
    "service_type": "PREPAID",
    "auto_bill_outstanding": true,
    "setup_fee": {
      "currency_code": "USD",
      "value": "10.0"
    },
    "setup_fee_failure_action": "CONTINUE",
    "payment_failure_threshold": 3
  },
  "taxes": {
    "percentage": "10.0",
    "inclusive": false
  },
  "quantity_supported": false,
  "create_time": "2021-08-09T11:32:53Z",
  "update_time": "2021-08-09T11:32:53Z",
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/billing/plans/P-4DB5144860082564AMEIREZI",
      "rel": "self",
      "method": "GET",
      "encType": "application/json"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/billing/plans/P-4DB5144860082564AMEIREZI",
      "rel": "edit",
      "method": "PATCH",
      "encType": "application/json"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/billing/plans/P-4DB5144860082564AMEIREZI/deactivate",
      "rel": "self",
      "method": "POST",
      "encType": "application/json"
    }
  ]
}
**/
