name: CI Web

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install packages and build
        run: |
          yarn install --immutable
          yarn build
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_PUBLIC_KEY: ${{ secrets.SUPABASE_PUBLIC_KEY }}
          SUPABASE_PRIVATE_KEY: ${{ secrets.SUPABASE_PRIVATE_KEY }}
          SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}

      - name: Check linting
        run: yarn lint

      - name: Build typescript
        run: yarn tsc

      - name: Remove tsc build
        run: rm -rf build

      - name: Test
        run: yarn test --coverage

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ./coverage/
      #     flags: unittests
      #     name: codecov-umbrella
      #     fail_ci_if_error: false
      #     path_to_write_report: ./coverage/codecov_report.gz
