name: Deploy production on release
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install packages and build
        run: |
          yarn install --immutable
          yarn build
        env:
          SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          SUPABASE_PUBLIC_KEY: ${{ secrets.PROD_SUPABASE_PUBLIC_KEY }}
          SUPABASE_PRIVATE_KEY: ${{ secrets.PROD_SUPABASE_PRIVATE_KEY }}
          SUPABASE_JWT_SECRET: ${{ secrets.PROD_SUPABASE_JWT_SECRET }}

      - name: CP 404.html
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GH_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WECOUNT_BF552 }}'
          projectId: wecount-bf552
          channelId: live
